name: test_fast_linux

###  https://github.com/arita37/awesome-actions#static-analysis

on:
  push:
    branches:
      #- run_train
      #- multi


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
   
    - name: Set up Python 3.6.*
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.*
      
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
      

    ##### Git Credemtials  ##################################################
    #- name: ssh_gen
    #  uses: webfactory/ssh-agent@v0.2.0
    #  with:
    #    ssh-private-key: ${{ secrets.GIT_RSA }}
                

    ########################################################################
    #- uses: actions/cache@v1
    #  id: cache
    #  with:
    #    path: ~/.cache/pip
    #    key: ${{ runner.os }}-pip-${{ hashFiles('**/install/requirements.txt') }}
    #    restore-keys: |
    #      ${{ runner.os }}-pip-
   

    - name: Cache pipenv virtualenv
      id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/Python/
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/install/py36.txt') }}
          

    - name: Install numpy
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: pip install numpy==1.18.2   pillow==6.2.1  scipy
      

    - name: Install repo requirements  1
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
           pip install -r   install/py36.txt
           pip install pyod==0.8.5

    - name: Install repo requirements   2
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run:  |
        ls .
        #pip install -r install/requirements_fake.txt

    #- name: Install repo
    #  run: pip install -e . -r install/py36.txt  --no-deps


    - name: test_import
      run: |
           python -c "import core_run;   print(core_run)"
           python -c "import os, numpy ; print(os)"
           pip list
           # python -c "import tensorflow, torch ; print(tensorflow); print(torch)"


    ########  Test running 
    #- name: run_all
    #  run: |
    #      mkdir -p    /home/runner/work/log_tmp/  
    #      chmod -R 777 . && ztest/run_fast.sh    2>&1 | tee   /home/runner/work/log_tmp/run_fast.py

    - name: python titanic_classifier.py  train
      # continue-on-error: true
      run:  |
            python titanic_classifier.py  train    --nsample 1000
            python titanic_classifier.py  predict  --nsample 1000

         

    - name: python example/classifier/classifier_multi.py  train    --nsample 10000   
      # continue-on-error: true
      run:  |
            python example/classifier/classifier_multi.py  train    --nsample 10000
            echo ""    

 
 


    #- name: ml_test_function
    #  run: ml_test --do test_functions    2>&1 | tee  cd /home/runner/work/mlmodels/mlmodels_store/log_import/log_functions.py


    #- name: ml_test
    #  run: ml_test
      
        

    - name: log_gitcommit
      run: |
           python core_test.py  log_remote_push --name test_fast_linux

# https://ianwhitestone.work/AWS-Serverless-Deployments-With-Github-Actions/
#
#
#
#
